### ISSUE TITLE
[Bug]: Can't use version 2.3.5 on MCreator 2023.1

### ISSUE THREAD

**Issue by EntiteeStudios** [Azzy380/Attributes#14]
### What happened?

When i updated the version of the plugin, i can no longer create or edit attribute mod elements, but the existing ones are still there. it also says when i check the Manage Plugins tab that Attributes is not fully loaded

### Generator version

Forge 1.18.2

### MCreator version

2023.1

**Comment by Azzy380** [comment]
Can you provide minimal example workspace? (like one with only attributes).
Also did you try upgrading MCreator to 2023.2? (if you will try, make a backup of your workspace).

**Comment by Azzy380** [comment]
Example workspace will give me info on what mcreator is arguing.
It might be because caused by plugin being built for mcreator 2023.2 an some code changes between 2023.1 and 2023.2 might be the issue, but without I'm not sure atm.

If this would be the case, then then I think you'd have to update mcreator.
Eventually you can try 2.3.4, which is available in releases tab on github or going back to 2.3.3 (if you didn't delete that version from your pc).

**Comment by EntiteeStudios** [comment]
i'll try attach an example workspace soon, but updating MCreator isn't an option because i have other plugins that are only available for 1.18.2 2023.1 and the Entity Attributes Modifier feature from the new update would be really helpful

**Comment by EntiteeStudios** [comment]
[Attribute Test.zip](https://github.com/Azzy380/Attributes/files/12388187/Attribute.Test.zip)

here's the zip file

**Comment by Azzy380** [comment]
It is caused by mcreator verison, but I'm going to provide seperate file for MCreator 2023.1 on plugins site :>
